# C#异常处理

[Microsoft C# 编码约定](https://learn.microsoft.com/zh-cn/dotnet/csharp/fundamentals/coding-style/coding-conventions)

[Microsoft C# 参考](https://learn.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2012/618ayhy6(v=vs.110))

[Microsoft C#文档](https://learn.microsoft.com/zh-cn/dotnet/csharp/)

在 C# 中，异常是在程序运行出错时引发的, 所有异常都派生自 System.Exception 类。

异常处理是一个处理运行时错误的过程，使用异常处理可以使程序在发生错误时保持正常运行。

- ### 异常处理的关键字

- ### try/catch语句

- ### C#中的异常类

- ### 自定义异常类

#### 异常处理的关键字

C# 中的异常处理基于四个关键字构建，分别是 try、catch、finally 和 throw。

- try：try 语句块中通常用来存放容易出现异常的代码，其后面紧跟一个或多个 catch 语句块；
- catch：catch 语句块用来捕获 try 语句块中的出现的异常；
- finally：finally 语句块用于执行特定的语句，不管异常是否被抛出都会执行；
- throw：throw 用来抛出一个异常。

#### try catch语句

其语法格式如下:

```C#
try{
   // 引起异常的语句
}catch( ExceptionName e1 ){
   // 错误处理代码
}catch( ExceptionName e2 ){
   // 错误处理代码
}
...
catch( ExceptionName eN ){
   // 错误处理代码
}finally{
   // 要执行的语句
}
```

列出多个 catch 语句块来捕获不同类型的异常，以防止 try 语句块在不同的情况下产生多个异常。

```C#
using System;
namespace c.sharp
{
    class Demo
    {
        static void Main(string[] args) 
        {
            try{ 
                int a = 123; 
                int b = 0; 
                int x = a / b; 
            }catch (Exception e) {
                Console.WriteLine("捕获到的异常：{0}", e);
            }finally{
                Console.WriteLine("finally 语句块中的代码"); 
            }
            Console.WriteLine("程序中的其它代码"); 
        }
    }
}
/*
捕获到的异常：System.DivideByZeroException: 尝试除以零。
   在 c.biancheng.net.Demo.Main(String[] args)
finally 语句块中的代码
程序中的其它代码
*/
```

#### C#中的异常类

C# 中的异常类主要是从 System.Exception 类派生的,  比如: System.ApplicationException 和  System.SystemException

- System.ApplicationException 类支持由程序产生的异常，因此我们自定义的异常都应继承此类；
- System.SystemException 类是所有系统预定义异常的基类。

列举Sytem.SystemException 类派生的预定义异常类:

| 异常类                            | 描述                                         |
| --------------------------------- | -------------------------------------------- |
| System.IO.IOException             | 处理 I/O 错误                                |
| System.IndexOutOfRangeException   | 处理当方法引用超出范围的数组索引时产生的错误 |
| System.ArrayTypeMismatchException | 处理当数组类型不匹配时产生的错误             |
| System.NullReferenceException     | 处理引用一个空对象时产生的错误               |
| System.DivideByZeroException      | 处理当除以零时产生的错误                     |
| System.InvalidCastException       | 处理在类型转换期间产生的错误                 |
| System.OutOfMemoryException       | 处理空闲内存不足产生的错误                   |
| System.StackOverflowException     | 处理栈溢出产生的错误                         |

#### 自定义异常类

自定义的异常类都应继承 System.ApplicationException 类。自定义异常类的使用如下:

```C#
using System;

namespace c.sharp
{
    class Demo
    {
        static void Main(string[] args) 
        {
            TestUserDefinedException test = new TestUserDefinedException();
            try{
                test.validate(12);
            }catch(InvalidAgeException e){
                Console.WriteLine("InvalidAgeException: {0}", e);
            }
            Console.WriteLine("其它代码");
        }
    }
}
public class InvalidAgeException : ApplicationException
{
   public InvalidAgeException (string message): base(message)
   {
   }
}
public class TestUserDefinedException
{
   public void validate(int age)
   {
      if(age < 18)
      {
         throw (new InvalidAgeException("Sorry, Age must be greater than 18"));
      }
   }
}

/*
InvalidAgeException: InvalidAgeException: Sorry, Age must be greater than 18
   在 TestUserDefinedException.validate(Int32 age)
   在 c.biancheng.net.Demo.Main(String[] args)
其它代码
*/
```

#### 抛出异常

如果异常是直接或间接派生自 System.Exception 类，则可以在 catch 语句块中使用 throw 语句抛出该异常, 即重新引发该异常。throw语句的语法格式如下:

```
catch(Exception e) {
   ...
   Throw e
}
```

